embedding_provider: sentence_transformers
embedding_model: sentence-transformers/all-MiniLM-L6-v2
base_ip: localhost
port: '11434'
llm_provider: openai
llm_model: gpt-4o-mini
temperature: 0.0
max_tokens: 2061
stop: null
keep_alive: false
top_k: 40
top_p: 0.9
repeat_penalty: 1.2
seed: 197464410746652
rag_folder_name: Safiro2
query_type: global
community_level: 2
preset: Default
external_llm_api_key: ''
random: false
prime_directives: null
prompt: Who helped Safiro infiltrate the Zaltar Organisation?
response_format: json
precision: fp16
attention: sdpa
aspect_ratio: '16:9'
top_k_search: 3
