aspect_ratio: '1:1'
attention: sdpa
auto_combo: false
base_ip: localhost
batch_count: 1
clear_history: false
external_api_key: ''
history_steps: 10
keep_alive: false
llm_model: grok-vision-beta
llm_provider: xai
max_tokens: 2048
port: '11434'
precision: fp16
prime_directives: ''
random: false
repeat_penalty: 1.2
seed: 275
stop_string: null
strategy: normal
temperature: 0.7
top_k: 40
top_p: 0.9
user_prompt: ''
